// src/app/layout.tsx

import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

// Usa fuentes de Google Fonts válidas
const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Time fades away events",
  description: "Generated by Time fades away events",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${inter.variable} ${robotoMono.variable}`}>
      <head>
        <link rel="icon" href="/images/logo/RELOJ.png" type="image/png" />
      </head>
      <body className="antialiased overflow-x-hidden">
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
